HOBBIES = [
    "Reading",
    "Gardening",
    "Cooking",
    "Painting",
    "Photography",
    "Hiking",
    "Playing a musical instrument",
    "Writing",
    "Fishing",
    "Singing",
    "Dancing",
    "Yoga",
    "Knitting",
    "Cycling",
    "Collecting stamps",
    "Woodworking",
    "Playing video games",
    "Bird watching",
    "Pottery",
    "Sculpting",
    "Rock climbing",
    "Swimming",
    "Chess",
    "Running",
    "Traveling",
    "Volunteering",
    "Sewing",
    "Playing sports",
    "Drawing",
    "Learning a new language",
    "Meditation",
    "Astrology",
    "Calligraphy",
    "Scrapbooking",
    "Amateur radio",
    "Baking",
    "Camping",
    "Skydiving",
    "Chessboxing",
    "Metalworking",
    "Archery",
    "Jewelry making",
    "Stand-up comedy",
    "Skiing",
    "Diving",
    "Model building",
    "Whittling",
    "Surfing",
    "Ghost hunting",
    "Beekeeping",
    "Acting",
    "Sudoku",
    "Magic tricks",
    "Bungee jumping",
    "Parkour",
    "Extreme couponing",
    "Geocaching",
    "Origami",
    "Wine tasting",
    "Belly dancing",
    "Trekking",
    "Antiquing",
]
