FOOD_CATEGORIES = [
    "Italian",
    "French",
    "Chinese",
    "Japanese",
    "Indian",
    "Mexican",
    "Thai",
    "Mediterranean",
    "Greek",
    "Spanish",
    "Lebanese",
    "American",
    "Brazilian",
    "Vietnamese",
    "Korean",
    "Turkish",
    "Moroccan",
    "Ethiopian",
    "British",
    "Cajun",
    "German",
    "Peruvian",
    "Iranian",
    "Russian",
    "Portuguese",
    "South African",
    "Swedish",
    "Polish",
    "Middle Eastern",
    "Caribbean",
    "Cuban",
    "Filipino",
    "Hawaiian",
    "Vegan",
    "Gluten-Free",
    "Paleo",
    "Keto",
    "Comfort Food",
    "BBQ",
    "Seafood",
    "Vegetarian",
    "Halal",
    "Kosher",
    "Soul Food",
    "Bakery",
    "Desserts",
    "Beverages",
    "Breakfast",
    "Lunch",
    "Dinner",
    "Snacks",
    "Appetizer",
    "Salad",
    "Soup"
]
