questions = [
    "Which of the following is more likely? (A) This sentence ends with a period (B) This sentence ends with a full stop",
    "Which of the following is more accurate? (A) Apples are fruits (B) Apples are a type of produce",
    "Which of the following is more correct? (A) Snow is cold (B) Snow is freezing",
    "Which of the following is more true? (A) Books contain words (B) Books contain sentences",
    "Which of the following is more likely? (A) A year has 12 months (B) A year lasts for 365 days",
    "Which of the following is more accurate? (A) Water is necessary for life (B) Water is essential for survival",
    "Which of the following is more correct? (A) Humans breathe oxygen (B) Humans inhale oxygen",
    "Which of the following is more true? (A) Cats are mammals (B) Cats are a type of pet",
    "Which of the following is more likely? (A) The sun rises in the east (B) The sun sets in the west",
    "Which of the following is more accurate? (A) Flowers bloom in spring (B) Flowers blossom in spring",
    "Which of the following is more correct? (A) Cars use gasoline for fuel (B) Cars use petrol for fuel",
    "Which of the following is more true? (A) A triangle has three sides (B) A triangle has three corners",
    "Which of the following is more likely? (A) Bees make honey (B) Bees produce honey",
    "Which of the following is more accurate? (A) A clock shows time (B) A clock displays time",
    "Which of the following is more correct? (A) Trees produce oxygen (B) Trees emit oxygen",
    "Which of the following is more true? (A) Bread is made from flour (B) Bread is made from grain",
    "Which of the following is more likely? (A) Humans have five fingers on each hand (B) Humans have ten fingers in total",
    "Which of the following is more accurate? (A) Dogs are known to be loyal (B) Dogs are known to be man's best friend",
    "Which of the following is more correct? (A) People need sleep to rest (B) People need sleep to recover",
    "Which of the following is more true? (A) Birds can fly (B) Birds have the ability to fly",
    "Which of the following is more likely? (A) A week has seven days (B) A week lasts for 168 hours",
    "Which of the following is more accurate? (A) Rain falls from the sky (B) Rain comes down from the sky",
    "Which of the following is more correct? (A) The moon orbits the earth (B) The moon goes around the earth",
    "Which of the following is more true? (A) Music can be heard (B) Music can be listened to",
    "Which of the following is more likely? (A) Fish live in water (B) Fish exist in water",
    "Which of the following is more accurate? (A) Fire can burn (B) Fire can cause burns",
    "Which of the following is more correct? (A) Sugar is sweet (B) Sugar tastes sweet",
    "Which of the following is more true? (A) Grass is green (B) Grass appears green",
    "Which of the following is more likely? (A) The earth rotates on its axis (B) The earth spins on its axis",
    "Which of the following is more accurate? (A) Humans are social beings (B) Humans are social creatures",
    "Which of the following is more correct? (A) A bicycle has two wheels (B) A bicycle has a pair of wheels",
    "Which of the following is more true? (A) Money can be spent (B) Money can be used to buy things",
    "Which of the following is more likely? (A) Stars twinkle at night (B) Stars shimmer at night",
    "Which of the following is more accurate? (A) An apple falls due to gravity (B) An apple is pulled down by gravity",
    "Which of the following is more correct? (A) Light travels faster than sound (B) Sound travels slower than light",
    "Which of the following is more true? (A) Plants need sunlight to grow (B) Plants require sunlight for photosynthesis",
    "Which of the following is more likely? (A) Humans have a heartbeat (B) Humans have a pulse",
    "Which of the following is more accurate? (A) Ice is solid water (B) Ice is the solid form of water",
    "Which of the following is more correct? (A) A baby cries when it's hungry (B) A baby cries when it needs food",
    "Which of the following is more true? (A) A door can be opened (B) A door can be unlocked",
    "Which of the following is more likely? (A) A kite flies in the sky (B) A kite soars in the sky",
    "Which of the following is more accurate? (A) A pen is used to write (B) A pen is used for writing",
    "Which of the following is more correct? (A) A rainbow appears after rain (B) A rainbow is seen after rain",
    "Which of the following is more true? (A) A turtle has a shell (B) A turtle is covered by a shell",
    "Which of the following is more likely? (A) People smile when they are happy (B) People grin when they are pleased",
    "Which of the following is more accurate? (A) A river flows towards the sea (B) A river runs towards the sea",
    "Which of the following is more correct? (A) An elephant has a long trunk (B) An elephant has an extended trunk",
    "Which of the following is more true? (A) A mirror reflects light (B) A mirror bounces back light",
    "Which of the following is more likely? (A) A book has pages (B) A book contains pages",
    "Which of the following is more accurate? (A) A camera takes pictures (B) A camera captures images",
    "Which of the following is more correct? (A) A boat floats on water (B) A boat stays afloat on water",
]
